"""Initial migration

Revision ID: 0d769d43fd0d
Revises: 
Create Date: 2026-04-26 09:26:31.618810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d769d43fd0d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('available_vacation_days', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('available_off_days', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'available_off_days')
    op.drop_column('users', 'available_vacation_days')
    # ### end Alembic commands ###
